### ISSUE TITLE
Support streaming logs

### ISSUE THREAD

**Issue by stephenjamieson** [bieniu/nextdns#172]
/logs/stream endpoint - https://nextdns.github.io/api/#streaming

**Comment by bieniu** [comment]
Please describe what is the use case of log stream?

**Comment by stephenjamieson** [comment]
Hey bieniu, I believe it would be useful to action on live logs, such as alerts.

**Comment by bieniu** [comment]
How exactly do you want to use it? From terminal? From your python script?

**Comment by stephenjamieson** [comment]
Script

**Comment by agnosticlines** [comment]
Hey I know this issue was marked as stale but if you'd be willing I'd love support for this, would allow me to stream logs into my SIEM solution!

**Comment by bieniu** [comment]
Of course the PR is most welcome.

**Comment by agnosticlines** [comment]
> Of course the PR is most welcome.

I'll look into it when I get some free time :) Thanks!
