### ISSUE TITLE
 the config/settings page don't work well on chrome in windows using high contrast 

### ISSUE THREAD

**Issue by leao-nardo** [bieniu/nextdns#219]
https://github.com/yokoffing/NextDNS-Config/issues/44 as i said there and was told to put here
windows high contrast theme dark black . makes the toggle buttons show as all black with just a border line .
there's no way to tell if the buttons are on or off .
in the allowlist page the button are like but i can tell if on/off , because when its off the text/url become shadowed/grayed .
if u make the settings page like this too it can be usable .

**Comment by bieniu** [comment]
You definitely got the wrong repository. First read the description, then open an issue.
