### ISSUE TITLE
Support switches for enabling and disable parental features

### ISSUE THREAD

**Issue by johntdyer** [bieniu/nextdns#22]
Would be awesome to be able to enable or disable things like TikTok or Youtube individually... .Kinda like this project does 

https://github.com/rhijjawi/NextDNS-API/blob/main/nextdnsapi/api.py

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/58234/180090750-073df45d-0f75-42b4-8088-e74e480454b1.png">

**Comment by bieniu** [comment]
My plan is to add as many features as possible. I'm starting my vacation tomorrow and I'll take care of it when I come back.

**Comment by bieniu** [comment]
I quickly added `block_tiktok` setting. Other services need to be added in a similar way. Unfortunately, changing the state of this setting does not work. We need to explain with NextDNS what correct request is needed (there is no such information in the documentation).

Currently we make `patch` request with data `{"id": "tiktok", "active": True}` to url: `https://api.nextdns.io/profiles/<profile_id>/parentalControl`.

**Comment by johntdyer** [comment]
Yea, it seems to require the `hex:` notation to work... I've updated a ticket on patching w/ NextDNS

https://help.nextdns.io/t/60hwq5q/patching-arrays

**Comment by johntdyer** [comment]
@bieniu  they responded in [my ticket](https://help.nextdns.io/t/q6hwnmf/patching-parentalcontrols-requires-hex-code).  TLDR, you have to add "Youtube" in the parental controls before you can enable or disable it.  Seems odd, as I've stated in the ticket...

**Comment by johntdyer** [comment]
ok, did some digging and found that the api enumerates the supported services with a GET against https://api.nextdns.io/parentalControl/services.  If you need to get the hex code you have to do this function to convert it to base16 I guess.

```
function StringToHex(e) {
  for (var t = unescape(encodeURIComponent(e)), n = "", r = 0; r < t.length; r++) n += t.charCodeAt(r).toString(16);
  return "hex:" + n.substring(n.length - 30)
}


```
png / Logo is the URL 

so "https://www.youtube.com" becomes https://favicons.nextdns.io/hex:7777772e796f75747562652e636f6d@2x.png

and the hex for enablement is the ID, so "youtube" becomes https://api.nextdns.io/profiles/xxxxx/parentalControl/services/hex:796f7574756265

So thinking if it is a supported service, listed in the /services response and we try to enable it and it returns a 404 we know its just not added.  We then catch that , add the service, and then perform the action ?  Thoughts?

**Comment by bieniu** [comment]
> So thinking if it is a supported service, listed in the /services response and we try to enable it and it returns a 404 we know its just not added. We then catch that , add the service, and then perform the action ? Thoughts?

I used exactly such logic.

**Comment by johntdyer** [comment]
![](https://www.kindpng.com/picc/m/220-2206970_high-five-virtual-high-five-meme-hd-png.png)

**Comment by bieniu** [comment]
For the last five switches, only the first word should be capitalised, eg. `Block social network`. Besides, the entity descriptions look good. You have to wait for the release of the new version of the backend library before opening PR with this change.
