### ISSUE TITLE
Contact info

### ISSUE THREAD

**Issue by yegors** [bieniu/nextdns#379]
Hi Maciej,

Sorry to post this here, but I'm looking to get in touch with you regarding your NextDNS related projects. Do you have a contact email somewhere? 

Thanks

Yegor

**Comment by bieniu** [comment]
Disclosing an email address on GitHub is not a good idea. Spammers' bots will intercept it. 
We can talk here. How can I help you?

**Comment by yegors** [comment]
If you can drop me a line (my email is public already) that would be awesome: yegor@controld.com 

My inquiry relates to the domain of my email.
